In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/ryano/werk/machine-learning-zoomcamp/.venv/lib/python3.11/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [8]:
a = np.array([1, 2, 3,2.5])
a

array([1. , 2. , 3. , 2.5])

In [10]:
a[2] =10

In [ ]:
a

array([ 1. ,  2. , 10. ,  2.5])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])